// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlwogGYT41STGgZdaentXG854Fxv2t9K0',
    appId: '1:174536441327:android:8b7aba45a991c3285c4a1a',
    messagingSenderId: '174536441327',
    projectId: 'tripmate-675c8',
    databaseURL: 'https://tripmate-675c8-default-rtdb.firebaseio.com',
    storageBucket: 'tripmate-675c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8s9TLIShjHjzX17OwneGqGPsqZzMA9G8',
    appId: '1:174536441327:ios:91e93d742589d3735c4a1a',
    messagingSenderId: '174536441327',
    projectId: 'tripmate-675c8',
    databaseURL: 'https://tripmate-675c8-default-rtdb.firebaseio.com',
    storageBucket: 'tripmate-675c8.firebasestorage.app',
    iosClientId: '174536441327-rqdkhisgf5kegfmpksr2b4mnk1p2d9qt.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripmates',
  );
}
